In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
from scipy import linalg as la
sp.init_printing() 
import warnings
warnings.filterwarnings("ignore")

## Goals and Commands

#### Goals
1. Dot Producs
2. Norm
3. Gram-Schmidt Process
4. QR-factorization

#### Commands
1. norm()
2. GramSchmidt()
3. linalg.qr()


#### Dot Product
There are few ways to do dot product in Jupyter:

In [4]:
v=np.array([1,2,3])
u=np.array([-1,2,5])

In [6]:
# matrix multiplication 
u@v

18

In [9]:
# using inner product command (inner product is more general name for dot product)
np.inner(u,v)

18

In [15]:
# Product with SymPy
a=sp.Matrix(u)
b=sp.Matrix(v)
a.T*b

[18]

To find norm is easy too:

In [25]:
np.linalg.norm(u)

In [26]:
la.norm(u)

In [27]:
a.norm()

### Example

Let $A=\begin{bmatrix} 1 & 1 & 2 \\ 2 & 5 & 0 \\ 4 & 7 & 4 \end{bmatrix}$. Show that Row(A) is orthogonal to Nul(A)

#### Solution

In [29]:
A=sp.Matrix([[1,1,2],[2,5,0],[4,7,4]])
row=A.rowspace()
nul=A.nullspace()
row,nul

⎛                         ⎡⎡-10/3⎤⎤⎞
⎜                         ⎢⎢     ⎥⎥⎟
⎜[[1  1  2], [0  3  -4]], ⎢⎢ 4/3 ⎥⎥⎟
⎜                         ⎢⎢     ⎥⎥⎟
⎝                         ⎣⎣  1  ⎦⎦⎠

Note both row and nul are lists containing vectors, so we will have to use indecies. To check orthogonality we just need to find all pairwise dot products. Since, row contains row vectors, we don't need to use transpose:

In [30]:
row[0]*nul[0]

[0]

In [31]:
row[1]*nul[0]

[0]

Both dot products are zero. Hence, both spaces are orthogonal to each other.
#### End of solution

Next, lets explore null space commands in more details:

In [36]:
A=np.array([[1,1,2],[5,5,10],[4,4,8]])
N=la.null_space(A)
N

array([[ 0.91287093, -0.        ],
       [-0.18257419,  0.89442719],
       [-0.36514837, -0.4472136 ]])

In [44]:
v1=N[:,0]
v2=N[:,1]

In [45]:
v1@v2

In [46]:
la.norm(v1)

In [47]:
la.norm(v2)

As you can see, la.null_space produces a matrix whose columns form orthonormal basis for Null space. Note that v1@v2=1.11022302462516 e−16. While this not zero, it is very very close to zero. In fact, it isn't a zero only due to a rounding error. 

The SymPy version (nullspace() ) doesn't provide orthonormal basis.

### Gram-Schmidt Process

SymPy includes are direct way to do Gram-Schmidt process:

#### Example

Orthogonalize column space for $A=\begin{bmatrix} 1 & 1 & 0 & 3\\ 2 & 5 & -1 & 3\\ 0 & 1 & 2 & 0\end{bmatrix}$

#### Solution

In [63]:
A=sp.Matrix([[1,1,0,3],[2,5,-1,3],[0,1,2,0]])
Col=A.columnspace()
sp.GramSchmidt(Col)


⎡⎡1⎤  ⎡-6/5⎤  ⎡ 1  ⎤⎤
⎢⎢ ⎥  ⎢    ⎥  ⎢    ⎥⎥
⎢⎢2⎥, ⎢3/5 ⎥, ⎢-1/2⎥⎥
⎢⎢ ⎥  ⎢    ⎥  ⎢    ⎥⎥
⎣⎣0⎦  ⎣ 1  ⎦  ⎣3/2 ⎦⎦

In [64]:
# Gram-Schmidt with normalization
sp.GramSchmidt(Col, orthonormal=True)

⎡        ⎡-3⋅√70 ⎤  ⎡ √14 ⎤⎤
⎢⎡ √5 ⎤  ⎢───────⎥  ⎢ ─── ⎥⎥
⎢⎢ ── ⎥  ⎢   35  ⎥  ⎢  7  ⎥⎥
⎢⎢ 5  ⎥  ⎢       ⎥  ⎢     ⎥⎥
⎢⎢    ⎥  ⎢ 3⋅√70 ⎥  ⎢-√14 ⎥⎥
⎢⎢2⋅√5⎥, ⎢ ───── ⎥, ⎢─────⎥⎥
⎢⎢────⎥  ⎢   70  ⎥  ⎢  14 ⎥⎥
⎢⎢ 5  ⎥  ⎢       ⎥  ⎢     ⎥⎥
⎢⎢    ⎥  ⎢  √70  ⎥  ⎢3⋅√14⎥⎥
⎢⎣ 0  ⎦  ⎢  ───  ⎥  ⎢─────⎥⎥
⎣        ⎣   14  ⎦  ⎣  14 ⎦⎦

#### End of Solution

### QR-factorization

This is an important type of marix factorization for many reasons. One of them is that in A=QR, the columns of Q are orthonormal basis of Col(A). This, in one go, provides a way to find basis for column space and to orthogonalize a set of vectors using NumPy or SciPy. (Note while sympy can do QR factorization as well, usually you have to manually round numbers as it will always try to be precise and use roots. Therefore, usually NumPy is a prefered way).

QR factorization will be even more important later when we discuss least-square approximation and PCA.

#### Example

Find orthonormal basis of $A=\begin{bmatrix} 1 & 1 & 0 & 3\\ 2 & 5 & -1 & 3\\ 0 & 1 & 2 & 0\end{bmatrix}$ using QR-factorization

#### Solution

In [66]:
A=np.array([[1,1,0,3],[2,5,-1,3],[0,1,2,0]])
Q, R = np.linalg.qr(A)

In [67]:
Q

array([[-0.4472136 ,  0.71713717,  0.53452248],
       [-0.89442719, -0.35856858, -0.26726124],
       [-0.        , -0.5976143 ,  0.80178373]])

In [68]:
R

array([[-2.23606798, -4.91934955,  0.89442719, -4.02492236],
       [ 0.        , -1.67332005, -0.83666003,  1.07570575],
       [ 0.        ,  0.        ,  1.87082869,  0.80178373]])

In [78]:
# Let's check the norms of columns of Q
la.norm(Q[0]), la.norm(Q[1]), la.norm(Q[2])

In [80]:
# Let's check orthogonality
Q[0]@Q[1], Q[0]@Q[2],Q[1]@Q[2]

#### End of Solution

Finally here is the SymPy way:

In [81]:
sp.matrices.MatrixBase.QRdecomposition(sp.Matrix(A))

⎛⎡ √5   -3⋅√70    √14 ⎤  ⎡    11⋅√5  -2⋅√5    9⋅√5  ⎤⎞
⎜⎢ ──   ───────   ─── ⎥  ⎢√5  ─────  ──────   ────  ⎥⎟
⎜⎢ 5       35      7  ⎥  ⎢      5      5       5    ⎥⎟
⎜⎢                    ⎥  ⎢                          ⎥⎟
⎜⎢2⋅√5   3⋅√70   -√14 ⎥  ⎢     √70    √70    -9⋅√70 ⎥⎟
⎜⎢────   ─────   ─────⎥, ⎢0    ───    ───    ───────⎥⎟
⎜⎢ 5       70      14 ⎥  ⎢      5      10       70  ⎥⎟
⎜⎢                    ⎥  ⎢                          ⎥⎟
⎜⎢        √70    3⋅√14⎥  ⎢            √14     3⋅√14 ⎥⎟
⎜⎢ 0      ───    ─────⎥  ⎢0     0     ───     ───── ⎥⎟
⎝⎣         14      14 ⎦  ⎣             2        14  ⎦⎠